language: node_js
node_js:
  - "0.10"
  - "0.12"
addons:
  firefox: "38.0"
  postgresql: "9.3"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp test/config/postgresql.json.travis test/config/postgresql.json
install:
  - npm install -g npm
  - npm install
env:
  - TEST_SUITE=compile
  - TEST_SUITE=coveralls
  - TEST_SUITE=lint
  - TEST_SUITE=test
script: "npm run $TEST_SUITE"
